services:
    db:
      image: postgres:16-alpine
      environment:
        POSTGRES_DB: reading_list
        POSTGRES_USER: reading_list_app
        POSTGRES_PASSWORD: password
      volumes:
        - postgres-db:/var/lib/postgresql/data
      networks:
        pgnodeapp:
          aliases:
            - "postgres"

    app:
      build: .
      image: nodeapp
      networks:
        - pgnodeapp
      ports:
        - "80:8080"
      environment:
        DB_USERNAME: reading_list_app
        DB_PASSWORD: password
        DB_DATABASE: reading_list
        DB_HOST: postgres
        NODE_ENV: development
      volumes:
        - ".:/app"
      depends_on:
        - "db"
      command: ["./wait-for", "postgres:5432", "--", "npm", "run", "build-start"]
      extra_hosts:
        - "host.docker.internal:host-gateway"  # This ensures host.docker.internal works

volumes:
  postgres-db: {}

networks:
  pgnodeapp:
    driver: bridge
